using OrchestFlowAI.Domain.Enums;

namespace OrchestFlowAI.Domain.Entities;

/// <summary>
/// Represents the execution details of an individual node within a workflow.
/// Tracks the node's execution state, input/output data, retries, and other metadata.
/// </summary>
public sealed class NodeExecution
{
    /// <summary>
    /// Gets the unique identifier of this node execution.
    /// </summary>
    public Guid Id { get; private set; }

    /// <summary>
    /// Gets the unique identifier of the parent workflow execution.
    /// </summary>
    public Guid WorkflowExecutionId { get; private set; }

    /// <summary>
    /// Gets the unique identifier of the workflow node.
    /// </summary>
    public string NodeId { get; private set; } = default!;

    /// <summary>
    /// Gets the type of the node being executed.
    /// </summary>
    public string NodeType { get; private set; } = default!;

    /// <summary>
    /// Gets the execution status of the node.
    /// </summary>
    public NodeExecutionStatus Status { get; private set; }

    /// <summary>
    /// Gets the date and time when the node execution started, if applicable.
    /// </summary>
    public DateTime? StartedAt { get; private set; }

    /// <summary>
    /// Gets the date and time when the node execution was completed, if applicable.
    /// </summary>
    public DateTime? CompletedAt { get; private set; }

    /// <summary>
    /// Gets the input data for the node in serialized JSON format, if applicable.
    /// </summary>
    public string? InputJson { get; private set; }

    /// <summary>
    /// Gets the output data generated by the node in serialized JSON format, if applicable.
    /// </summary>
    public string? OutputJson { get; private set; }

    /// <summary>
    /// Gets the error message describing the failure reason, if applicable.
    /// </summary>
    public string? ErrorMessage { get; private set; }

    /// <summary>
    /// Gets the 1-based attempt number for this node execution. Incremented on each retry.
    /// </summary>
    public int AttemptNumber { get; private set; } = 1;

    /// <summary>
    /// Gets the number of retries attempted for this node execution.
    /// </summary>
    public int RetryCount { get; private set; }

    /// <summary>
    /// Gets the sequential step number in the workflow execution.
    /// </summary>
    public int Step { get; private set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="NodeExecution"/> class.
    /// </summary>
    private NodeExecution() { }

    /// <summary>
    /// Factory method to create and initialize a new node execution instance.
    /// </summary>
    /// <param name="workflowExecutionId">The ID of the parent workflow execution.</param>
    /// <param name="nodeId">The unique identifier of the workflow node.</param>
    /// <param name="nodeType">The type of the node being executed.</param>
    /// <param name="step">The sequential step number in the workflow execution.</param>
    /// <returns>A new instance of NodeExecution.</returns>
    public static NodeExecution Create(Guid workflowExecutionId, string nodeId, string nodeType, int step)
        => new()
        {
            Id = Guid.NewGuid(),
            WorkflowExecutionId = workflowExecutionId,
            NodeId = nodeId,
            NodeType = nodeType,
            Status = NodeExecutionStatus.Pending,
            Step = step
        };

    /// <summary>
    /// Marks the node execution as running and records its input data.
    /// </summary>
    /// <param name="inputJson">The input data for the node in serialized JSON format.</param>
    public void Start(string? inputJson)
    {
        Status = NodeExecutionStatus.Running;
        StartedAt = DateTime.UtcNow;
        InputJson = inputJson;
    }

    /// <summary>
    /// Marks the node execution as successful and records its output data.
    /// </summary>
    /// <param name="outputJson">The output data generated by the node in serialized JSON format.</param>
    public void Succeed(string outputJson)
    {
        Status = NodeExecutionStatus.Succeeded;
        OutputJson = outputJson;
        CompletedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Marks the node execution as failed, records the error message, and increments the retry count.
    /// </summary>
    /// <param name="errorMessage">Details about why the node execution failed.</param>
    public void Fail(string errorMessage)
    {
        Status = NodeExecutionStatus.Failed;
        ErrorMessage = errorMessage;
        CompletedAt = DateTime.UtcNow;
        RetryCount++;
    }

    /// <summary>
    /// Increments the attempt number, indicating a retry is being performed.
    /// </summary>
    public void IncrementAttempt()
    {
        AttemptNumber++;
        RetryCount++;
    }

    /// <summary>
    /// Places the node execution into a waiting-for-approval state.
    /// </summary>
    /// <param name="payloadJson">The payload data related to the approval process.</param>
    public void WaitForApproval(string payloadJson)
    {
        Status = NodeExecutionStatus.WaitingForApproval;
        OutputJson = payloadJson;
    }

    /// <summary>
    /// Marks the node execution as skipped.
    /// </summary>
    public void Skip()
    {
        Status = NodeExecutionStatus.Skipped;
        CompletedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Cancels the node execution and records the cancellation time.
    /// </summary>
    public void Cancel()
    {
        Status = NodeExecutionStatus.Cancelled;
        CompletedAt = DateTime.UtcNow;
    }
}